// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6PqydWvxExga5YvYcUJpkpTOgxqtiu4Y',
    appId: '1:1094047448255:web:d0f886700064ca61435a0a',
    messagingSenderId: '1094047448255',
    projectId: 'eshop-flutter-f0375',
    authDomain: 'eshop-flutter-f0375.firebaseapp.com',
    databaseURL: 'https://eshop-flutter-f0375-default-rtdb.firebaseio.com',
    storageBucket: 'eshop-flutter-f0375.firebasestorage.app',
    measurementId: 'G-TE2722EXNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQOH7oYhYZA4MBgR5PMqZsGFpjpcu8be8',
    appId: '1:1094047448255:android:12cc63b9c51422b3435a0a',
    messagingSenderId: '1094047448255',
    projectId: 'eshop-flutter-f0375',
    databaseURL: 'https://eshop-flutter-f0375-default-rtdb.firebaseio.com',
    storageBucket: 'eshop-flutter-f0375.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfS3U_XhiES_fN6cFcldOWf1HdgPnx4UU',
    appId: '1:1094047448255:ios:f6d4100f27252d3c435a0a',
    messagingSenderId: '1094047448255',
    projectId: 'eshop-flutter-f0375',
    databaseURL: 'https://eshop-flutter-f0375-default-rtdb.firebaseio.com',
    storageBucket: 'eshop-flutter-f0375.firebasestorage.app',
    iosBundleId: 'com.example.eShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfS3U_XhiES_fN6cFcldOWf1HdgPnx4UU',
    appId: '1:1094047448255:ios:f6d4100f27252d3c435a0a',
    messagingSenderId: '1094047448255',
    projectId: 'eshop-flutter-f0375',
    databaseURL: 'https://eshop-flutter-f0375-default-rtdb.firebaseio.com',
    storageBucket: 'eshop-flutter-f0375.firebasestorage.app',
    iosBundleId: 'com.example.eShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6PqydWvxExga5YvYcUJpkpTOgxqtiu4Y',
    appId: '1:1094047448255:web:d40719a7146195b7435a0a',
    messagingSenderId: '1094047448255',
    projectId: 'eshop-flutter-f0375',
    authDomain: 'eshop-flutter-f0375.firebaseapp.com',
    databaseURL: 'https://eshop-flutter-f0375-default-rtdb.firebaseio.com',
    storageBucket: 'eshop-flutter-f0375.firebasestorage.app',
    measurementId: 'G-GHMV604B4R',
  );
}
